apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: rate-limiter5
  name: rate-limiter5
spec:
  containers:
  - name: rate-limiter5
    image: bmuschko/nodejs-business-app:1.0.0
    ports:
    - containerPort: 8080
    resources:
      requests:
        memory: "512Mi"
        cpu: "3"
      limits:
        memory: "1G"
        cpu: "4"
