apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx
    team: helix
  name: nginx
  namespace: persistence
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
    team: helix
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
    team: helix
  name: nginx
  namespace: persistence
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      team: helix
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
        team: helix
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
